[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[build.headers]
  "/*" = [
    "Cache-Control: public, max-age=0, must-revalidate",
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "https://wa.me/6285758047504?text=Halo"
  status = 301

[[redirects]]
  from = "/website"
  to = "https://www.rolandowebdev.space/"
  status = 301

[[redirects]]
  from = "/github"
  to = "https://github.com/rolandowebdev"
  status = 301
